### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by alsajeeb** [nshefeek/docGPT-v.0.0.1#1]
WHY R U NOT USING CHUNKING AND STORE THE RESULTS INTO A VECTOR DB

**Comment by nshefeek** [comment]
When I was building the system I was considering it as a generic solution. So performing chunking of the source documents and performing embedding would have resulted in loss of context, which in turn would have affected the accuracy of the RAG system.

But feel free to try it yourself.

Thanks for the input.
